### ISSUE TITLE
Option to disable player transparency for spectators

### ISSUE THREAD

**Issue by zealain** [KZGlobalTeam/gokz#204]
**[Original report](https://bitbucket.org/kztimerglobalteam/gokz/issue/204) by zer0.k (Bitbucket: [zer0k_z](https://bitbucket.org/zer0k_z), ).**

----------------------------------------

Transparency is added so players can see the map without being blocked by others. Spectators \(and mostly GOTV client\) wouldn’t care as much about this, so an option to remove this would be nice. 

This might be taxing on server resource though, so giving the server owner the choice to enable this feature would be a plus.

**Comment by Cinyan10** [comment]
Can you solve this problem now? When playing multiplayer games, I see that others are in a transparent state. I am very uncomfortable with it

**Comment by zer0k-z** [comment]
While it is possible to do such thing, it requires extra dependencies (SendProxy), and allegedly it takes way too much resources from the server for it to be feasible, and much much more than `!hide` even, which is already quite expensive by itself. That's why there's nothing done regarding this issue yet.

**Comment by zealain** [comment]
Something being even more taxing than `!hide` definitely doesn't seem feasible. This might be reconsidered again if a better solution is found. Also can already be done globally as explained in https://github.com/KZGlobalTeam/gokz/issues/357#issuecomment-1221358306.
